# build.yaml

# This file defines how to build ZMK firmware for your custom board + shield.
# For SuperMini NRF52840, use the Seeeduino XIAO NRF52840 board target.

include:
  - board: xiao_ble
    shield: boardsource_3x4
